# coding: utf-8

"""
    Spring PACE Product Client Software Server

    This section describes the API calls and their usage to interact with the Spring Network.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@springlabs.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import springlabs
from springlabs.api.attestation_groups_api import AttestationGroupsApi  # noqa: E501
from springlabs.rest import ApiException


class TestAttestationGroupsApi(unittest.TestCase):
    """AttestationGroupsApi unit test stubs"""

    def setUp(self):
        self.api = springlabs.api.attestation_groups_api.AttestationGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_attestation_group_by_id(self):
        """Test case for get_attestation_group_by_id

        Get information about a previously created attestation group by ID  # noqa: E501
        """
        pass

    def test_revoke_attestation_group_by_id(self):
        """Test case for revoke_attestation_group_by_id

        Revoke an existing attestation group  # noqa: E501
        """
        pass

    def test_upsert_attestation_group_by_id(self):
        """Test case for upsert_attestation_group_by_id

        Update or create an attestation group  # noqa: E501
        """
        pass

    def test_upsert_attestation_groups(self):
        """Test case for upsert_attestation_groups

        Update or create registry attestation groups in bulk  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
