# coding: utf-8

"""
    Spring PACE Product Client Software Server

    This section describes the API calls and their usage to interact with the Spring Network.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@springlabs.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import springlabs
from springlabs.api.inquiries_api import InquiriesApi  # noqa: E501
from springlabs.rest import ApiException


class TestInquiriesApi(unittest.TestCase):
    """InquiriesApi unit test stubs"""

    def setUp(self):
        self.api = springlabs.api.inquiries_api.InquiriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_inquiry(self):
        """Test case for create_inquiry

        Purchase an inquiry on a Subject (a property)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
