# coding: utf-8

"""
    Spring PACE Product Client Software Server

    This section describes the API calls and their usage to interact with the Spring Network.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@springlabs.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import springlabs
from springlabs.api.root_api import RootApi  # noqa: E501
from springlabs.rest import ApiException


class TestRootApi(unittest.TestCase):
    """RootApi unit test stubs"""

    def setUp(self):
        self.api = springlabs.api.root_api.RootApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_root(self):
        """Test case for get_root

        Root endpoint for the service.  # noqa: E501
        """
        pass

    def test_healthz(self):
        """Test case for healthz

        Health check endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
