# coding: utf-8

"""
    Spring PACE Product Client Software Server

    This section describes the API calls and their usage to interact with the Spring Network.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@springlabs.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from springlabs.configuration import Configuration


class AttestationGroupDigest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'error': 'AttestationGroupError',
        'normalization': 'NormalizationInfo'
    }

    attribute_map = {
        'error': 'error',
        'normalization': 'normalization'
    }

    def __init__(self, error=None, normalization=None, local_vars_configuration=None):  # noqa: E501
        """AttestationGroupDigest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._error = None
        self._normalization = None
        self.discriminator = None

        if error is not None:
            self.error = error
        self.normalization = normalization

    @property
    def error(self):
        """Gets the error of this AttestationGroupDigest.  # noqa: E501


        :return: The error of this AttestationGroupDigest.  # noqa: E501
        :rtype: AttestationGroupError
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this AttestationGroupDigest.


        :param error: The error of this AttestationGroupDigest.  # noqa: E501
        :type: AttestationGroupError
        """

        self._error = error

    @property
    def normalization(self):
        """Gets the normalization of this AttestationGroupDigest.  # noqa: E501


        :return: The normalization of this AttestationGroupDigest.  # noqa: E501
        :rtype: NormalizationInfo
        """
        return self._normalization

    @normalization.setter
    def normalization(self, normalization):
        """Sets the normalization of this AttestationGroupDigest.


        :param normalization: The normalization of this AttestationGroupDigest.  # noqa: E501
        :type: NormalizationInfo
        """
        if self.local_vars_configuration.client_side_validation and normalization is None:  # noqa: E501
            raise ValueError("Invalid value for `normalization`, must not be `None`")  # noqa: E501

        self._normalization = normalization

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AttestationGroupDigest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AttestationGroupDigest):
            return True

        return self.to_dict() != other.to_dict()
