# coding: utf-8

"""
    Spring PACE Product Client Software Server

    This section describes the API calls and their usage to interact with the Spring Network.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@springlabs.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from springlabs.configuration import Configuration


class PageLinks(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'next': 'str',
        'prev': 'str',
        '_self': 'str'
    }

    attribute_map = {
        'next': 'next',
        'prev': 'prev',
        '_self': 'self'
    }

    def __init__(self, next=None, prev=None, _self=None, local_vars_configuration=None):  # noqa: E501
        """PageLinks - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._next = None
        self._prev = None
        self.__self = None
        self.discriminator = None

        if next is not None:
            self.next = next
        if prev is not None:
            self.prev = prev
        self._self = _self

    @property
    def next(self):
        """Gets the next of this PageLinks.  # noqa: E501

        URI for the next page of data (if any)  # noqa: E501

        :return: The next of this PageLinks.  # noqa: E501
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this PageLinks.

        URI for the next page of data (if any)  # noqa: E501

        :param next: The next of this PageLinks.  # noqa: E501
        :type: str
        """

        self._next = next

    @property
    def prev(self):
        """Gets the prev of this PageLinks.  # noqa: E501

        URI for the previous page of data (if any)  # noqa: E501

        :return: The prev of this PageLinks.  # noqa: E501
        :rtype: str
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this PageLinks.

        URI for the previous page of data (if any)  # noqa: E501

        :param prev: The prev of this PageLinks.  # noqa: E501
        :type: str
        """

        self._prev = prev

    @property
    def _self(self):
        """Gets the _self of this PageLinks.  # noqa: E501

        URI for this page of data.  # noqa: E501

        :return: The _self of this PageLinks.  # noqa: E501
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this PageLinks.

        URI for this page of data.  # noqa: E501

        :param _self: The _self of this PageLinks.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and _self is None:  # noqa: E501
            raise ValueError("Invalid value for `_self`, must not be `None`")  # noqa: E501

        self.__self = _self

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PageLinks):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PageLinks):
            return True

        return self.to_dict() != other.to_dict()
